// LLM Providers configuration

import type { LLMProvider, LLMModel } from "./types"

export const LLM_PROVIDERS: LLMProvider[] = [
  {
    id: "openai",
    name: "OpenAI",
    status: "connected",
    apiKeyRequired: true,
    models: [
      {
        id: "gpt-4.1",
        providerId: "openai",
        name: "gpt-4.1",
        displayName: "GPT-4.1",
        contextWindow: 1000000,
        maxOutput: 32768,
        inputCost: 2.0,
        outputCost: 8.0,
        capabilities: ["text", "code", "vision", "function-calling", "json-mode", "streaming"],
        speed: "medium",
        quality: "premium",
      },
      {
        id: "gpt-4.1-mini",
        providerId: "openai",
        name: "gpt-4.1-mini",
        displayName: "GPT-4.1 Mini",
        contextWindow: 1000000,
        maxOutput: 32768,
        inputCost: 0.4,
        outputCost: 1.6,
        capabilities: ["text", "code", "vision", "function-calling", "json-mode", "streaming"],
        speed: "fast",
        quality: "high",
      },
      {
        id: "o3",
        providerId: "openai",
        name: "o3",
        displayName: "o3 (Reasoning)",
        contextWindow: 200000,
        maxOutput: 100000,
        inputCost: 10.0,
        outputCost: 40.0,
        capabilities: ["text", "code", "function-calling", "streaming"],
        speed: "slow",
        quality: "premium",
      },
    ],
  },
  {
    id: "anthropic",
    name: "Anthropic",
    status: "connected",
    apiKeyRequired: true,
    models: [
      {
        id: "claude-sonnet-4",
        providerId: "anthropic",
        name: "claude-sonnet-4",
        displayName: "Claude Sonnet 4",
        contextWindow: 200000,
        maxOutput: 64000,
        inputCost: 3.0,
        outputCost: 15.0,
        capabilities: ["text", "code", "vision", "function-calling", "json-mode", "streaming"],
        speed: "medium",
        quality: "premium",
      },
      {
        id: "claude-haiku-3.5",
        providerId: "anthropic",
        name: "claude-haiku-3.5",
        displayName: "Claude Haiku 3.5",
        contextWindow: 200000,
        maxOutput: 8192,
        inputCost: 0.8,
        outputCost: 4.0,
        capabilities: ["text", "code", "vision", "function-calling", "streaming"],
        speed: "fast",
        quality: "high",
      },
    ],
  },
  {
    id: "google",
    name: "Google",
    status: "connected",
    apiKeyRequired: true,
    models: [
      {
        id: "gemini-2.5-pro",
        providerId: "google",
        name: "gemini-2.5-pro",
        displayName: "Gemini 2.5 Pro",
        contextWindow: 1000000,
        maxOutput: 65536,
        inputCost: 1.25,
        outputCost: 10.0,
        capabilities: ["text", "code", "vision", "function-calling", "json-mode", "streaming"],
        speed: "medium",
        quality: "premium",
      },
      {
        id: "gemini-2.5-flash",
        providerId: "google",
        name: "gemini-2.5-flash",
        displayName: "Gemini 2.5 Flash",
        contextWindow: 1000000,
        maxOutput: 65536,
        inputCost: 0.15,
        outputCost: 0.6,
        capabilities: ["text", "code", "vision", "function-calling", "streaming"],
        speed: "fast",
        quality: "high",
      },
    ],
  },
  {
    id: "ollama",
    name: "Ollama (Local)",
    status: "connected",
    apiKeyRequired: false,
    baseUrl: "http://localhost:11434",
    models: [
      {
        id: "llama3.3:70b",
        providerId: "ollama",
        name: "llama3.3:70b",
        displayName: "Llama 3.3 70B",
        contextWindow: 128000,
        maxOutput: 8192,
        inputCost: 0,
        outputCost: 0,
        capabilities: ["text", "code", "function-calling", "streaming"],
        speed: "slow",
        quality: "premium",
      },
      {
        id: "qwen2.5-coder:32b",
        providerId: "ollama",
        name: "qwen2.5-coder:32b",
        displayName: "Qwen 2.5 Coder 32B",
        contextWindow: 128000,
        maxOutput: 8192,
        inputCost: 0,
        outputCost: 0,
        capabilities: ["text", "code", "streaming"],
        speed: "medium",
        quality: "high",
      },
      {
        id: "deepseek-r1:32b",
        providerId: "ollama",
        name: "deepseek-r1:32b",
        displayName: "DeepSeek R1 32B",
        contextWindow: 64000,
        maxOutput: 8192,
        inputCost: 0,
        outputCost: 0,
        capabilities: ["text", "code", "streaming"],
        speed: "medium",
        quality: "high",
      },
    ],
  },
  {
    id: "groq",
    name: "Groq",
    status: "connected",
    apiKeyRequired: true,
    models: [
      {
        id: "llama-3.3-70b-versatile",
        providerId: "groq",
        name: "llama-3.3-70b-versatile",
        displayName: "Llama 3.3 70B (Groq)",
        contextWindow: 128000,
        maxOutput: 32768,
        inputCost: 0.59,
        outputCost: 0.79,
        capabilities: ["text", "code", "function-calling", "streaming"],
        speed: "fast",
        quality: "premium",
      },
      {
        id: "mixtral-8x7b-32768",
        providerId: "groq",
        name: "mixtral-8x7b-32768",
        displayName: "Mixtral 8x7B (Groq)",
        contextWindow: 32768,
        maxOutput: 32768,
        inputCost: 0.24,
        outputCost: 0.24,
        capabilities: ["text", "code", "streaming"],
        speed: "fast",
        quality: "high",
      },
    ],
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    status: "connected",
    apiKeyRequired: true,
    models: [
      {
        id: "deepseek-chat",
        providerId: "deepseek",
        name: "deepseek-chat",
        displayName: "DeepSeek V3",
        contextWindow: 64000,
        maxOutput: 8192,
        inputCost: 0.14,
        outputCost: 0.28,
        capabilities: ["text", "code", "function-calling", "streaming"],
        speed: "fast",
        quality: "premium",
      },
      {
        id: "deepseek-reasoner",
        providerId: "deepseek",
        name: "deepseek-reasoner",
        displayName: "DeepSeek R1",
        contextWindow: 64000,
        maxOutput: 8192,
        inputCost: 0.55,
        outputCost: 2.19,
        capabilities: ["text", "code", "streaming"],
        speed: "slow",
        quality: "premium",
      },
    ],
  },
]

export function getAllModels(): LLMModel[] {
  return LLM_PROVIDERS.flatMap((p) => p.models)
}

export function getModelById(id: string): LLMModel | undefined {
  return getAllModels().find((m) => m.id === id)
}

export function getProviderById(id: string): LLMProvider | undefined {
  return LLM_PROVIDERS.find((p) => p.id === id)
}

export function getModelsByCapability(capability: string): LLMModel[] {
  return getAllModels().filter((m) => m.capabilities.includes(capability as any))
}
