{{- if .Values.nats.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "neoland.fullname" . }}-nats
  labels:
    {{- include "neoland.labels" . | nindent 4 }}
    app.kubernetes.io/component: nats
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.nats.clientPort }}
      targetPort: client
      protocol: TCP
      name: client
    - port: {{ .Values.nats.monitorPort }}
      targetPort: monitor
      protocol: TCP
      name: monitor
  selector:
    {{- include "neoland.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nats
{{- end }}
