apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neoland.fullname" . }}-secrets
  labels:
    {{- include "neoland.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ include "neoland.jwtSecret" . | quote }}
  {{- if .Values.postgresql.enabled }}
  database-url: {{ include "neoland.databaseUrl" . | quote }}
  {{- end }}
  {{- if .Values.config.auth.googleClientId }}
  google-client-id: {{ .Values.config.auth.googleClientId | quote }}
  {{- end }}
  {{- if .Values.config.auth.googleClientSecret }}
  google-client-secret: {{ .Values.config.auth.googleClientSecret | quote }}
  {{- end }}
  {{- if .Values.config.auth.githubClientId }}
  github-client-id: {{ .Values.config.auth.githubClientId | quote }}
  {{- end }}
  {{- if .Values.config.auth.githubClientSecret }}
  github-client-secret: {{ .Values.config.auth.githubClientSecret | quote }}
  {{- end }}
