apiVersion: v1
kind: Service
metadata:
  name: {{ include "neoland.fullname" . }}
  labels:
    {{- include "neoland.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: rest
      port: {{ .Values.service.restPort }}
      targetPort: rest
      protocol: TCP
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "neoland.selectorLabels" . | nindent 4 }}
